routes/user.php
<?php
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

Route::middleware('checkActiveUser')->group(function (){
    Route::controller(UserController::class)->group(function (){
        Route::prefix('users')->group(function (){
            Route::as('users.')->group(function (){
                Route::get('/', 'index')->name('index')
                    ->middleware('hasPermission:users,users.index');
                Route::get('/list', 'list')->name('list')
                    ->middleware('hasPermission:users,users.index');
                Route::get('/show/{id}', 'show')->name('show')
                    ->middleware('hasPermission:users,users.show');
                Route::get('edit/{id}', 'edit')->name('edit')
                    ->middleware('hasPermission:users,users.update');
                Route::put('update/{id}', 'update')->name('update')
                    ->middleware('hasPermission:users,users.update');
                Route::delete('delete/{id}', 'destroy')->name('delete')
                    ->middleware('hasPermission:users,users.delete');
            });
        });
    });
});

routes/web.php
<?php

use App\Helpers\Helper;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Helper::requireRoute();

Route::get('/', function () {
    return view('welcome');
})->name('welcome')->middleware('checkActiveUser');

app/Models/User.php
<?php

namespace App\Models;

use App\Traits\HandleImage;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HandleImage;

    const ROLE_ADMIN = 'Admin';
    const PATH = 'images/users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'gender',
        'birthday',
        'avatar',
        'email',
        'phone',
        'password',
        'address',
        'activated',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected function avatar(): Attribute
    {
        $this->setPath(self::PATH);
        return Attribute::make(
            get: fn($avatar) => ($this->getImageFullPath($avatar))
        );
    }

    protected function password(): Attribute
    {
        return Attribute::make(
            get: fn($password) => $password,
            set: fn($password) => bcrypt($password)
        );
    }

    protected function birthday(): Attribute
    {
        return Attribute::make(
            get: fn($birth) => (empty($birth) ? '' :
                Carbon::parse($birth)->format('d/m/Y')),
            set: fn($birth) => Carbon::createFromFormat('d/m/Y', $birth)->format('Y-m-d')
        );
    }

    public function scopeOrWithName($query, $name)
    {
        return $name ? $query->orWhereFullText('name', $name) : null;
    }

    public function scopeOrWithEmail($query, $email)
    {
        return $email ? $query->orWhereFullText('email', $email) : null;
    }

    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'roles_users', 'user_id', 'role_id');
    }

    public function syncRoles($rolesId): array
    {
        return $this->roles()->sync($rolesId);
    }

    public function hasPermission($permissionName): bool
    {
        if ($this->isAdmin()) {
            return true;
        }

        foreach ($this->roles as $role) {
            if ($role->hasPermission($permissionName)) {
                return true;
            }
        }

        return false;
    }

    public function isAdmin(): bool
    {
        return $this->hasRole(self::ROLE_ADMIN);
    }

    public function hasRole($roleName): bool
    {
        return $this->roles()->where('name', $roleName)->exists();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Users\UpdateRequest;
use App\Services\UserService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\Response;

class UserController extends Controller
{
    public UserService $userService;
    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request): View
    {
        return view('users.index');
    }

    public function list(Request $request): Response
    {
        $users = $this->userService->list($request);
        $view = view('users.paginate', compact('users'))->render();
        return $this->sendResponse(Response::HTTP_OK, $view);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id): Response
    {
        $user = $this->userService->findOrFail($id);
        $view = view('users.show', compact('user'))->render();
        return $this->sendResponse(Response::HTTP_OK, $view);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id): Response
    {
        $user = $this->userService->findOrFail($id);
        $roles = $this->userService->listRoles();
        $view = view('users.update', compact(['user', 'roles']))->render();
        return $this->sendResponse(Response::HTTP_OK, $view);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRequest $request, string $id): Response
    {
        $user = $this->userService->update($request, $id);
        $view = view('users.show', compact('user'))->render();
        $message = 'The user has been updated successfully.';
        return $this->sendResponse(Response::HTTP_OK, $view, $message);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id): Response
    {
        $this->userService->delete($id);
        return $this->sendResponse(Response::HTTP_NO_CONTENT);
    }
}

resources/views/users/index.blade.php
@extends('layouts.main')
@section('contents')
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>User Tables</h1>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- /.row -->
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-tools float-left">
                                    <form id="form-search" action="{{ route('users.list') }}" method="GET"
                                          class="input-group input-group-sm" style="width: 150%;">
                                        @csrf
                                        @method('GET')
                                        <input autocomplete="off"
                                               id="name" type="text" name="name"
                                               class="form-control name" placeholder="Search user">
                                        <div class="input-group-append">
                                            <button type="submit" class="btn btn-default">
                                                <i class="fas fa-search"></i>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body table-responsive p-0">
                                <div id="table-data">
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>
    <div id="modal">

    </div>
@endsection

resources/views/users/paginate.blade.php
@php use App\Helpers\Helper; @endphp
<table class="table table-hover text-nowrap">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Image</th>
        <th>Gender</th>
        <th>Email</th>
        <th>Status</th>
        <th>Action(s)</th>
    </tr>
    </thead>
    <tbody>
    @if($users->isNotEmpty())
        @foreach($users as $user)
            <tr>
                <td>
                    {{ $user->id }}
                </td>
                <td>
                    {{ $user->name }}
                </td>
                <td>
                    <img src="{{ $user->avatar }}" alt=""
                         style="width:110px; height:110px; object-fit: cover;"
                         class="img-thumbnail img-circle">
                </td>
                <td>
                    {{ Helper::getGender($user->gender) }}
                </td>
                <td>
                    {{ $user->email }}
                </td>
                <td>
                    {!! Helper::getStatus($user->activated) !!}
                </td>
                <td>
                    @hasPermission('users', 'users.show')
                    <a href="{{ route('users.show', $user->id) }}"
                       class="btn btn-sm btn-info btn-open-modal" data-toggle="modal">
                        <i class="fas fa-eye"></i>
                    </a>
                    @endhasPermission

                    @hasPermission('users', 'users.update')
                    <a href="{{ route('users.edit', $user->id) }}"
                       class="btn btn-sm btn-secondary btn-open-modal" data-toggle="modal">
                        <i class="fas fa-edit"></i>
                    </a>
                    @endhasPermission

                    @hasPermission('users', 'users.delete')
                    <a href="{{ route('users.delete', $user->id) }}"
                       class="btn btn-sm btn-danger btn-delete">
                        <i class="fas fa-trash"></i>
                    </a>
                    @endhasPermission
                </td>
            </tr>
        @endforeach
    @else
        <tr>
            <td colspan="7" class="text-center">
                <span style="color: red">No data found.</span>
            </td>
        </tr>
    @endif
    </tbody>
</table>
<div class="mt-3 mr-2 ml-2">
    {{ $users->links() }}
</div>

resources/views/users/show.blade.php
@php use App\Helpers\Helper; @endphp
<div class="modal fade" id="modal-form">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Detail user</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-3">

                        <!-- Profile Image -->
                        <div class="card card-primary card-outline">
                            <div class="card-body box-profile">
                                <div class="d-flex flex-column align-items-center">
                                    <img class="profile-user-img img-fluid img-circle"
                                         src="{{ $user->avatar }}"
                                         alt="User profile picture"
                                         style="width:250px; height:220px; object-fit: cover;">
                                </div>

                                <h3 class="profile-username text-center">
                                    {{ $user->name }}
                                </h3>

                                <p class="text-muted text-center">
                                    {{ $user->email }}
                                </p>

                                <ul class="list-group list-group-unbordered mb-3">
                                    <li class="list-group-item">
                                        <b>Roles</b>
                                        <a class="float-right">
                                            @foreach($user->roles as $role)
                                                {!! $role->name . '</br>' !!}
                                            @endforeach
                                        </a>
                                    </li>
                                    <li class="list-group-item">
                                        <b>Phone</b>
                                        <a class="float-right">
                                            {{ Helper::convertPhone($user->phone) }}
                                        </a>
                                    </li>
                                    <li class="list-group-item">
                                        <b>Status</b>
                                        <a class="float-right">
                                            {!! Helper::getStatus($user->activated) !!}
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                        <!-- About Me Box -->

                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-9">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">About Me</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <strong><i class="fas fa-venus-mars mr-1"></i> Gender</strong>

                                <p class="text-muted">
                                    {{ Helper::getGender($user->gender) }}
                                </p>

                                <hr>
                                <strong><i class="fas fa-book mr-1"></i> Birthday</strong>

                                <p class="text-muted">
                                    {{ $user->birthday }}
                                </p>

                                <hr>

                                <strong><i class="fas fa-map-marker-alt mr-1"></i> Location</strong>

                                <p class="text-muted">
                                    {!! $user->address !!}
                                </p>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

resources/views/users/update.blade.php
@php use App\Helpers\Helper; @endphp
<div class="modal fade" id="modal-form">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Product Update</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="form-data" action="{{ route('users.update', $user->id) }}" method="POST"
                      enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="row">
                        <!-- left column -->
                        <div class="col-md-3">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <!-- form start -->
                                <div class="card-body">
                                    <div class="d-flex justify-content-center">
                                        <div class="d-flex flex-column align-items-center">
                                            <img style="width:250px; height:250px; object-fit: cover;"
                                                 id="image-preview"
                                                 class="img-thumbnail img-circle"
                                                 src="{{ $user->avatar }}" alt="">
                                            <div class="form-group ml-3 mt-2">
                                                <div class="input-group">
                                                    <div class="custom-file">
                                                        <input class="input-image" name="avatar" type="file" id="avatar"
                                                               accept="image/png, image/jpeg">
                                                        <span id="avatar-error" class="error invalid-feedback"></span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (left) -->
                        <!-- right column -->
                        <div class="col-md-4">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <!-- form start -->
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="roles">Roles</label>
                                        <select name="roleIds[]" class="select2" id="input-roles" multiple="multiple"
                                                data-placeholder="Select roles" style="width: 100%;">
                                            <option value="">---->Select roles<----</option>
                                            @foreach($roles as $role)
                                                <option value="{{ $role->id }}"
                                                @foreach($user->roles as $hasRole)
                                                    {{ $hasRole->id === $role->id ? 'selected' : '' }}
                                                    @endforeach
                                                >
                                                    {{ $role->name }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                    <div class="form-group required">
                                        <label for="name" class="control-label">User name:</label>
                                        <input value="{{ $user->name }}" name="name" type="text" class="form-control"
                                               id="input-name" placeholder="Enter name">
                                        <span id="name-error" class="error invalid-feedback"></span>
                                    </div>
                                    <div class="form-group required">
                                        <label for="gender" class="control-label">Gender</label>
                                        <div class="row" id="input-gender">
                                            <div class="col-sm-6">
                                                <!-- checkbox -->
                                                <div class="form-group">
                                                    <div class="custom-control custom-radio">
                                                        <input @checked($user->gender === 0) name="gender" value="0"
                                                               class="custom-control-input" type="radio" id="women">
                                                        <label for="women" class="custom-control-label">Women</label>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-sm-6">
                                                <!-- radio -->
                                                <div class="form-group">
                                                    <div class="custom-control custom-radio">
                                                        <input @checked($user->gender === 1) name="gender" value="1"
                                                               class="custom-control-input" type="radio" id="men">
                                                        <label for="men" class="custom-control-label">Men</label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <span id="gender-error" class="error invalid-feedback"></span>
                                    </div>

                                    <div class="form-group required">
                                        <label for="birthday" class="control-label">Birthday:</label>
                                        <div class="input-group">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i
                                                        class="far fa-calendar-alt"></i></span>
                                            </div>
                                            <input id="input-birthday" name="birthday" value="{{ $user->birthday }}"
                                                   type="text" class="form-control" data-inputmask-alias="datetime"
                                                   data-inputmask-inputformat="dd/mm/yyyy" data-mask>
                                            <span id="birthday-error" class="error invalid-feedback"></span>
                                        </div>
                                        <!-- /.input group -->
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-control custom-checkbox">
                                            <input name="activated"
                                                   @checked($user->activated === 1) class="custom-control-input"
                                                   type="checkbox" id="activated" value="1">
                                            <label for="activated" class="custom-control-label">Active</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                        <div class="col-md-5">
                            <!-- general form elements -->
                            <div class="card card-primary">
                                <!-- form start -->
                                <div class="card-body">
                                    <div class="form-group required">
                                        <label for="email" class="control-label">Email address</label>
                                        <input disabled name="email" value="{{ $user->email }}"
                                               type="email" class="form-control" id="input-email"
                                               placeholder="Enter email">
                                        <span id="email-error" class="error invalid-feedback"></span>
                                    </div>
                                    <div class="form-group required">
                                        <label for="phone" class="control-label">Phone</label>
                                        <input name="phone" value="{{ $user->phone }}"
                                               type="text" class="form-control" id="input-phone"
                                               placeholder="Enter phone">
                                        <span id="phone-error" class="error invalid-feedback"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input name="password"
                                               type="password" class="form-control" id="input-password"
                                               placeholder="Enter password">
                                        <span id="password-error" class="error invalid-feedback"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="address" class="description">Address</label>
                                        <textarea name="address" class="form-control" rows="3" id="input-address"
                                                  placeholder="Enter ..."></textarea>
                                        <span id="address-error" class="error invalid-feedback"></span>
                                    </div>
                                </div>
                                <!-- /.card-body -->
                            </div>
                            <!-- /.card -->
                        </div>
                        <!--/.col (right) -->
                    </div>
                </form>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary btn-save">Save</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<script src="{{ asset('assets') }}/plugins/moment/moment.min.js"></script>
<script src="{{ asset('assets') }}/plugins/inputmask/jquery.inputmask.min.js"></script>
<script>
    $(function () {
        $('.select2').select2()
        //Datemask dd/mm/yyyy
        $('#datemask').inputmask('dd/mm/yyyy', {'placeholder': 'dd/mm/yyyy'})
        //Datemask2 mm/dd/yyyy
        $('#datemask2').inputmask('mm/dd/yyyy', {'placeholder': 'mm/dd/yyyy'})
        //Money Euro
        $('[data-mask]').inputmask()
    })
</script>